# lang: yaml
linters-settings:
  custom:
    detectany:
      description: "custom linter: detect any"
      path: "detectany.so"  # 构建后的 linter 可执行文件路径

linters:
  disable-all: true
  enable:
    - detectany